### ISSUE TITLE
Test-dedicated pages

### ISSUE THREAD

**Issue by marc-lopez** [KRGG/RRS#29]
In reference to pull request #27 

**Suggestion**: All front-end only scenarios like text overflow, layout, and similar requirements are to tested in pages dedicated to that purpose.

**Rationale**: With using test-dedicated pages, we are assured that changes to the page used for the feature under test are better managed. Using production pages may or may not exhibit the desired front-end behavior in which tests are to be made as time passes and requirements are modified.

**Comment by noelsison** [comment]
I agree in the use of test-dedicated pages for now since we do not have finalized content yet and this enables us to test for extreme cases. 

But when we have finalized layouts and content, we should use production pages in addition to extreme test cases. To exhibit the desired front-end behavior, we will use a test database with content similar to the actual database (Example: We could use a snapshot of the actual database for testing purposes if there is sufficient data stored in it).

**Comment by marc-lopez** [comment]
I agree with this.
